Repository wchaws/serverless-image-handler, pull requests merged in 2021-07, with the labels that each got.

#11 chore: add inline doc
  source/ecs-image-handler/src/processor/index.ts
  source/ecs-image-handler/src/store.ts
Labels: documentation

#20 feat: add custom style delimiter '@!'
  source/ecs-image-handler/src/default.ts
  source/ecs-image-handler/src/index.ts
  source/ecs-image-handler/src/processor/image/index.ts
  source/ecs-image-handler/test/default.test.ts
  source/ecs-image-handler/test/processor/index.test.ts
Labels: enhancement

#21 Add Function [blur bright contrast crop grey format rotate sharpen]
  source/ecs-image-handler/src/processor/image/auto-orient.ts
  source/ecs-image-handler/src/processor/image/blur.ts
  source/ecs-image-handler/src/processor/image/bright.ts
  source/ecs-image-handler/src/processor/image/contrast.ts
  source/ecs-image-handler/src/processor/image/crop.ts
  source/ecs-image-handler/src/processor/image/format.ts
  source/ecs-image-handler/src/processor/image/grey.ts
  source/ecs-image-handler/src/processor/image/index.ts
  source/ecs-image-handler/src/processor/image/indexcrop.ts
  source/ecs-image-handler/src/processor/image/interlace.ts
  source/ecs-image-handler/src/processor/image/rotate.ts
  source/ecs-image-handler/src/processor/image/sharpen.ts
  source/ecs-image-handler/test/processor/image/auto-orient.test.ts
  source/ecs-image-handler/test/processor/image/blur.test.ts
  source/ecs-image-handler/test/processor/image/bright.test.ts
  source/ecs-image-handler/test/processor/image/contrast.test.ts
  source/ecs-image-handler/test/processor/image/crop.test.ts
  source/ecs-image-handler/test/processor/image/format.test.ts
  source/ecs-image-handler/test/processor/image/grey.test.ts
  source/ecs-image-handler/test/processor/image/indexcrop.test.ts
  source/ecs-image-handler/test/processor/image/interlace.test.ts
  source/ecs-image-handler/test/processor/image/rotate.test.ts
  source/ecs-image-handler/test/processor/image/sharpen.test.ts
Labels: enhancement

#30 feat: support use existing s3 bucket
  source/constructs/README.md
  source/constructs/lib/ecs-image-handler.ts
Labels: enhancement

#31 chore: set minimal node version to 12
  source/constructs/README.md
  source/ecs-image-handler/Dockerfile
  source/ecs-image-handler/package.json
Labels: enhancement

#35 chore: add trouble shooting in README and support change stack name
  source/constructs/README.md
  source/constructs/bin/constructs.ts
  source/ecs-image-handler/test/store.test.ts
Labels: documentation, enhancement

#38 fix: build error on node 12
  .github/workflows/build.yml
  source/constructs/package.json
Labels: documentation, enhancement

#39 chore: add tags
  source/constructs/bin/constructs.ts
Labels: enhancement
